# .readthedocs.yml
version: 2

# Use Ubuntu 22.04 and Python 3.12
build:
  os: ubuntu-22.04
  apt_packages:
    - pandoc  
  tools:
    python: "3.12"

# Point Sphinx at your conf.py
sphinx:
  configuration: docs/source/conf.py

# Install your package (with dev extras so all doc‐build deps are present)
python:
  install:
    - path: .
      extra_requirements: ["dev"]
