# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  apt_packages:
    - graphviz
    - pandoc

# Point Sphinx at the right conf.py
sphinx:
  configuration: docs/source/conf.py

# Install your package from the local path with dev dependencies
python:
  install:
    - path: ./pykal_core/
      extra_requirements: ["dev"]
