# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  apt_packages:
    - graphviz
    - pandoc

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - path: .
      extra_requirements: ["docs"]
