#!/usr/bin/env python3
"""Add callback simulation and plotting to turtlebot notebook."""

import json

nb_path = "docs/source/notebooks/tutorial/theory_to_python/turtlebot_state_estimation.ipynb"

with open(nb_path, 'r') as f:
    nb = json.load(f)

# Find the position to insert new cells (after callback wrapper, before experimentation)
cells = nb['cells']
insert_idx = None

for i, cell in enumerate(cells):
    # Find the callback wrapper cell (contains 'def initialize_turtlebot_system')
    if cell['cell_type'] == 'code' and 'def initialize_turtlebot_system' in ''.join(cell.get('source', [])):
        # Insert after this cell
        insert_idx = i + 1
        break

if insert_idx is None:
    print("Could not find callback wrapper cell!")
    exit(1)

# Cells to insert
new_cells = [
    # Markdown: explanation
    {
        "cell_type": "markdown",
        "id": "13c3c121",
        "metadata": {},
        "source": [
            "Now we can run the same simulation with a much cleaner interface. All system parameters can be configured at initialization, and the simulation loop becomes trivial:"
        ]
    },

    # Code: initialize and run simulation using callback
    {
        "cell_type": "code",
        "id": "bea7670d",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "# Initialize the complete TurtleBot navigation system\n",
            "np.random.seed(42)\n",
            "turtlebot_system = initialize_turtlebot_system(\n",
            "    # Initial states\n",
            "    xk_init=np.array([[0.0], [0.0], [0.0], [0.0], [0.0]]),\n",
            "    xhat_init=np.array([[0.0], [0.0], [0.0], [0.0], [0.0]]),\n",
            "    P_init=np.diag([0.1, 0.1, 0.1, 1.0, 1.0]),\n",
            "    # System parameters\n",
            "    dt=0.1,\n",
            "    Kv=0.5,\n",
            "    Komega=1.5,\n",
            "    # Kalman filter parameters\n",
            "    Q=np.diag([0.01, 0.01, 0.02, 0.1, 0.1]),\n",
            "    R=np.diag([0.05, 0.05, 0.1]),\n",
            "    # Waypoint parameters\n",
            "    waypoints=[\n",
            "        (2.0, 0.0, 0.0),\n",
            "        (2.0, 2.0, np.pi / 2),\n",
            "        (0.0, 2.0, np.pi),\n",
            "        (0.0, 0.0, -np.pi / 2),\n",
            "    ],\n",
            "    switch_time=15.0,\n",
            "    # Realistic corruption\n",
            "    use_realistic_corruption=True,\n",
            ")\n",
            "\n",
            "# Simulation time\n",
            "T_sim = 60.0\n",
            "dt = 0.1\n",
            "time_steps = np.arange(0, T_sim, dt)\n",
            "\n",
            "# Storage for results\n",
            "results = {\n",
            "    \"time\": [],\n",
            "    \"reference\": [],\n",
            "    \"command\": [],\n",
            "    \"true_state\": [],\n",
            "    \"measurement\": [],\n",
            "    \"estimate\": [],\n",
            "    \"estimation_error\": [],\n",
            "}\n",
            "\n",
            "# Run simulation\n",
            "for tk in time_steps:\n",
            "    output = turtlebot_system(tk)\n",
            "\n",
            "    results[\"time\"].append(output[\"time\"])\n",
            "    results[\"reference\"].append(output[\"reference\"])\n",
            "    results[\"command\"].append(output[\"command\"])\n",
            "    results[\"true_state\"].append(output[\"true_state\"])\n",
            "    results[\"measurement\"].append(output[\"measurement\"])\n",
            "    results[\"estimate\"].append(output[\"estimate\"])\n",
            "    results[\"estimation_error\"].append(output[\"estimation_error\"])\n",
            "\n",
            "# Convert to numpy arrays for plotting\n",
            "for key in [\"reference\", \"command\", \"true_state\", \"measurement\", \"estimate\", \"estimation_error\"]:\n",
            "    results[key] = np.array(results[key])"
        ]
    },

    # Code: visualize results
    {
        "cell_type": "code",
        "id": "e1c61893",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "# Visualize results\n",
            "fig, axs = plt.subplots(3, 2, figsize=(14, 12))\n",
            "\n",
            "# Plot 1: 2D Trajectory\n",
            "ax = axs[0, 0]\n",
            "ax.plot(\n",
            "    results[\"true_state\"][:, 0],\n",
            "    results[\"true_state\"][:, 1],\n",
            "    \"b-\",\n",
            "    label=\"True Trajectory\",\n",
            "    linewidth=2,\n",
            "    alpha=0.7,\n",
            ")\n",
            "ax.plot(\n",
            "    results[\"estimate\"][:, 0],\n",
            "    results[\"estimate\"][:, 1],\n",
            "    \"r--\",\n",
            "    label=\"Estimated Trajectory\",\n",
            "    linewidth=2,\n",
            "    alpha=0.7,\n",
            ")\n",
            "ax.scatter(\n",
            "    results[\"reference\"][:, 0],\n",
            "    results[\"reference\"][:, 1],\n",
            "    c=\"green\",\n",
            "    s=100,\n",
            "    marker=\"*\",\n",
            "    label=\"Waypoints\",\n",
            "    zorder=5,\n",
            ")\n",
            "ax.set_xlabel(\"X Position (m)\", fontsize=11)\n",
            "ax.set_ylabel(\"Y Position (m)\", fontsize=11)\n",
            "ax.set_title(\n",
            "    \"2D Trajectory Tracking (Callback Interface)\",\n",
            "    fontsize=13,\n",
            "    fontweight=\"bold\"\n",
            ")\n",
            "ax.legend()\n",
            "ax.grid(True, alpha=0.3)\n",
            "ax.axis(\"equal\")\n",
            "\n",
            "# Plot 2: X Position vs Time\n",
            "ax = axs[0, 1]\n",
            "ax.plot(\n",
            "    results[\"time\"],\n",
            "    results[\"true_state\"][:, 0],\n",
            "    \"b-\",\n",
            "    label=\"True X\",\n",
            "    alpha=0.7,\n",
            ")\n",
            "ax.plot(\n",
            "    results[\"time\"],\n",
            "    results[\"estimate\"][:, 0],\n",
            "    \"r--\",\n",
            "    label=\"Estimated X\",\n",
            "    alpha=0.7,\n",
            ")\n",
            "ax.scatter(\n",
            "    results[\"time\"][::10],\n",
            "    results[\"measurement\"][::10, 0],\n",
            "    c=\"gray\",\n",
            "    s=10,\n",
            "    alpha=0.3,\n",
            "    label=\"Measurements\",\n",
            ")\n",
            "ax.set_ylabel(\"X Position (m)\", fontsize=11)\n",
            "ax.set_title(\"X Position Over Time\", fontsize=13, fontweight=\"bold\")\n",
            "ax.legend()\n",
            "ax.grid(True, alpha=0.3)\n",
            "\n",
            "# Plot 3: Y Position vs Time\n",
            "ax = axs[1, 0]\n",
            "ax.plot(\n",
            "    results[\"time\"],\n",
            "    results[\"true_state\"][:, 1],\n",
            "    \"b-\",\n",
            "    label=\"True Y\",\n",
            "    alpha=0.7,\n",
            ")\n",
            "ax.plot(\n",
            "    results[\"time\"],\n",
            "    results[\"estimate\"][:, 1],\n",
            "    \"r--\",\n",
            "    label=\"Estimated Y\",\n",
            "    alpha=0.7,\n",
            ")\n",
            "ax.scatter(\n",
            "    results[\"time\"][::10],\n",
            "    results[\"measurement\"][::10, 1],\n",
            "    c=\"gray\",\n",
            "    s=10,\n",
            "    alpha=0.3,\n",
            "    label=\"Measurements\",\n",
            ")\n",
            "ax.set_ylabel(\"Y Position (m)\", fontsize=11)\n",
            "ax.set_title(\"Y Position Over Time\", fontsize=13, fontweight=\"bold\")\n",
            "ax.legend()\n",
            "ax.grid(True, alpha=0.3)\n",
            "\n",
            "# Plot 4: Heading vs Time\n",
            "ax = axs[1, 1]\n",
            "ax.plot(\n",
            "    results[\"time\"],\n",
            "    np.rad2deg(results[\"true_state\"][:, 2]),\n",
            "    \"b-\",\n",
            "    label=\"True Heading\",\n",
            "    alpha=0.7,\n",
            ")\n",
            "ax.plot(\n",
            "    results[\"time\"],\n",
            "    np.rad2deg(results[\"estimate\"][:, 2]),\n",
            "    \"r--\",\n",
            "    label=\"Estimated Heading\",\n",
            "    alpha=0.7,\n",
            ")\n",
            "ax.set_ylabel(\"Heading (degrees)\", fontsize=11)\n",
            "ax.set_title(\"Heading Over Time\", fontsize=13, fontweight=\"bold\")\n",
            "ax.legend()\n",
            "ax.grid(True, alpha=0.3)\n",
            "\n",
            "# Plot 5: Velocity Commands\n",
            "ax = axs[2, 0]\n",
            "ax.plot(\n",
            "    results[\"time\"],\n",
            "    results[\"command\"][:, 0],\n",
            "    \"g-\",\n",
            "    label=\"Linear Velocity\",\n",
            "    linewidth=1.5,\n",
            ")\n",
            "ax.set_ylabel(\"Linear Velocity (m/s)\", fontsize=11)\n",
            "ax.set_xlabel(\"Time (s)\", fontsize=11)\n",
            "ax.set_title(\"Control Commands\", fontsize=13, fontweight=\"bold\")\n",
            "ax.legend(loc=\"upper left\")\n",
            "ax.grid(True, alpha=0.3)\n",
            "\n",
            "ax_omega = ax.twinx()\n",
            "ax_omega.plot(\n",
            "    results[\"time\"],\n",
            "    results[\"command\"][:, 1],\n",
            "    \"purple\",\n",
            "    label=\"Angular Velocity\",\n",
            "    linewidth=1.5,\n",
            "    alpha=0.7,\n",
            ")\n",
            "ax_omega.set_ylabel(\"Angular Velocity (rad/s)\", fontsize=11, color=\"purple\")\n",
            "ax_omega.tick_params(axis=\"y\", labelcolor=\"purple\")\n",
            "ax_omega.legend(loc=\"upper right\")\n",
            "\n",
            "# Plot 6: Position Estimation Error\n",
            "ax = axs[2, 1]\n",
            "position_error = np.sqrt(\n",
            "    results[\"estimation_error\"][:, 0] ** 2 + results[\"estimation_error\"][:, 1] ** 2\n",
            ")\n",
            "ax.plot(\n",
            "    results[\"time\"],\n",
            "    position_error,\n",
            "    \"m-\",\n",
            "    label=\"Position Error\",\n",
            "    linewidth=1.5,\n",
            ")\n",
            "ax.set_xlabel(\"Time (s)\", fontsize=11)\n",
            "ax.set_ylabel(\"Position Error (m)\", fontsize=11)\n",
            "ax.set_title(\"Estimation Error Magnitude\", fontsize=13, fontweight=\"bold\")\n",
            "ax.legend()\n",
            "ax.grid(True, alpha=0.3)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "print(f\"Mean position error: {np.mean(position_error):.4f} m\")\n",
            "print(f\"Max position error: {np.max(position_error):.4f} m\")"
        ]
    }
]

# Insert the new cells
cells[insert_idx:insert_idx] = new_cells

# Update notebook
nb['cells'] = cells

with open(nb_path, 'w') as f:
    json.dump(nb, f, indent=1)

print(f"Successfully added callback simulation and plotting")
print(f"Total cells: {len(cells)}")
